export const LANDING_SCREEN = "LANDING_SCREEN";
export const HOME_SCREEN = "HOME_SCREEN";
export const WALLET_CONNECT_SCREEN = "WALLET_CONNECT_SCREEN";
export const QR_CODE_SCANNER_SCREEN = "QR_CODE_SCANNER_SCREEN";
export const TOKEN_SCREEN = "TOKEN_SCREEN";
export const PROPOSAL_SCREEN = "PROPOSAL_SCREEN";
