export const LANDING_SCREEN = "LANDING_SCREEN";
export const HOME_SCREEN = "HOME_SCREEN";
export const WALLET_CONNECT_SCREEN = "WALLET_CONNECT_SCREEN";
export const QR_CODE_SCANNER_SCREEN = "QR_CODE_SCANNER_SCREEN";
export const PROPOSAL_SCREEN = "PROPOSAL_SCREEN";
export const CUSTOM_WALLET_SCREEN = "CUSTOM_WALLET_SCREEN";
export const NETWORK_SCREEN = "NETWORK_SCREEN";
export const STRATEGY_SCREEN = "STRATEGY_SCREEN";
export const SPACE_SCREEN = "SPACE_SCREEN";
export const SETTINGS_SCREEN = "SETTINGS_SCREEN";
export const CONNECT_ACCOUNT_SCREEN = "CONNECT_ACCOUNT_SCREEN";
export const PROPOSAL_VOTES_SCREEN = "PROPOSAL_VOTES_SCREEN";
export const CREATE_PROPOSAL_SCREEN = "CREATE_PROPOSAL_SCREEN";
export const ADVANCED_SETTINGS_SCREEN = "ADVANCED_SETTINGS_SCREEN";
export const ABOUT_SCREEN = "ABOUT_SCREEN";
export const SPACE_SETTINGS_SCREEN = "SPACE_SETTINGS_SCREEN";
export const ONBOARDING = "ONBOARDING";
export const WALLET_SETUP_SCREEN = "WALLET_SETUP_SCREEN";
export const CHOOSE_PASSWORD_SCREEN = "CHOOSE_PASSWORD_SCREEN";
export const CHANGE_PASSWORD_SCREEN = "CHANGE_PASSWORD_SCREEN";
export const SEED_PHRASE_BACKUP_STEP1_SCREEN =
  "SEED_PHRASE_BACKUP_STEP1_SCREEN";
export const SEED_PHRASE_BACKUP_STEP2_SCREEN =
  "SEED_PHRASE_BACKUP_STEP2_SCREEN";
export const SEED_PHRASE_BACKUP_COMPLETE_SCREEN =
  "SEED_PHRASE_BACKUP_COMPLETE_SCREEN";
export const IMPORT_FROM_SEED_SCREEN = "IMPORT_FROM_SEED_SCREEN";
export const QR_CODE_SCREEN = "QR_CODE_SCREEN";
export const IMPORT_FROM_PRIVATE_KEY_SCREEN = "IMPORT_FROM_PRIVATE_KEY_SCREEN";
export const ACCOUNT_DETAILS_SCREEN = "ACCOUNT_DETAILS_SCREEN";
export const SHOW_PRIVATE_KEY_SCREEN = "SHOW_PRIVATE_KEY_SCREEN";
